#!/usr/bin/env php
<?php

// 配置本地  线上环境  1－测试　２－正式
define('APP_ENV', 1 );


define('DEBUG',true);
// 定义项目路径
define('APP_PATH', __DIR__ . '/application/');

// 加载框架引导文件
require __DIR__.'/thinkphp/console.php';
